kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-fw
  template:
    metadata:
      labels:
        app: webhook-fw
    spec:
      containers:
        - name: webhook-fw
          image: python-image:latest
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: my-python
spec:
  ports:
    - name: http-5000
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: python-app
